import { z } from 'zod/v4';
import type { NodeDefinition } from '../node/types';

export interface NodeReferenceDocument {
  markdown: string;
  warnings: readonly string[];
}

const GENERATED_COMMENT =
  '<!-- Generated by `midscene-test describe-nodes`. Do not edit directly. -->';

const WORKFLOW_STEP_CONTRACT = `## Workflow Step Contract

Each step uses a node name as its key. The \`$\` object contains engine metadata and is not part of the node input.

\`\`\`yaml
workflow:
  - node.name:
      prompt: Describe the task.
      $:
        timeout: 30000
        continue-on-error: false
\`\`\`

A string step value is shorthand for \`{ prompt: value }\`. Whether that input is valid depends on the node input schema.`;

const sortJsonValue = (value: unknown): unknown => {
  if (Array.isArray(value)) return value.map(sortJsonValue);
  if (typeof value !== 'object' || value === null) return value;

  return Object.fromEntries(
    Object.entries(value)
      .sort(([left], [right]) => (left < right ? -1 : left > right ? 1 : 0))
      .map(([key, child]) => [key, sortJsonValue(child)]),
  );
};

const assertSelfContainedRefs = (value: unknown, node: string): void => {
  if (Array.isArray(value)) {
    for (const child of value) assertSelfContainedRefs(child, node);
    return;
  }
  if (typeof value !== 'object' || value === null) return;

  for (const [key, child] of Object.entries(value)) {
    if (key === '$ref' && typeof child === 'string' && !child.startsWith('#')) {
      throw new Error(
        `Cannot describe node "${node}": inputSchema generated an external $ref.`,
      );
    }
    assertSelfContainedRefs(child, node);
  }
};

const toJsonSchema = (node: NodeDefinition<any, any, any>): unknown => {
  try {
    const schema = z.toJSONSchema(node.inputSchema!, {
      target: 'draft-2020-12',
      io: 'input',
      unrepresentable: 'throw',
      cycles: 'ref',
      reused: 'ref',
    });
    assertSelfContainedRefs(schema, node.name);
    return sortJsonValue(schema);
  } catch (error) {
    if (
      error instanceof Error &&
      error.message.startsWith(`Cannot describe node "${node.name}":`)
    ) {
      throw error;
    }
    throw new Error(
      `Cannot describe node "${node.name}": inputSchema contains a Zod type that cannot be represented as JSON Schema.`,
      { cause: error },
    );
  }
};

const renderNode = (
  node: NodeDefinition<any, any, any>,
  warnings: string[],
): string => {
  const sections = [`## \`${node.name}\``];

  if (node.title) sections.push(`**Title:** ${node.title.trim()}`);
  if (node.description) {
    sections.push(node.description.trim());
  } else {
    warnings.push(`node "${node.name}" has no description`);
    sections.push(
      `> Description not declared. Do not infer this node's behavior.`,
    );
  }

  sections.push('### Input Schema');
  if (node.inputSchema) {
    sections.push(
      `\`\`\`json\n${JSON.stringify(toJsonSchema(node), null, 2)}\n\`\`\``,
    );
  } else {
    warnings.push(`node "${node.name}" has no inputSchema`);
    sections.push(
      '> Input schema not declared. Do not invent input fields for this node.',
    );
  }

  return sections.join('\n\n');
};

export const renderNodeReference = (
  nodes: readonly NodeDefinition<any, any, any>[],
): NodeReferenceDocument => {
  const warnings: string[] = [];
  const sortedNodes = [...nodes].sort((left, right) =>
    left.name < right.name ? -1 : left.name > right.name ? 1 : 0,
  );
  const sections = [
    GENERATED_COMMENT,
    '# Midscene Test Node Reference',
    'This document describes the nodes registered by the current Test Project.',
    WORKFLOW_STEP_CONTRACT,
  ];

  if (sortedNodes.length === 0) {
    sections.push('No nodes are registered by the current Test Project.');
  } else {
    for (const node of sortedNodes) sections.push(renderNode(node, warnings));
  }

  return {
    markdown: `${sections.join('\n\n')}\n`,
    warnings,
  };
};
