packages:
  - apps/site
  - apps/chrome-extension
  - apps/report
  - packages/cli
  - packages/shared
  - packages/core
  - packages/visualizer
  - packages/web-integration
  - packages/evaluation
  - packages/android