[build]
  command = "pnpm install --ignore-scripts && pnpm run build" 
  publish = "doc_build"

[build.environment]
  NODE_VERSION = "18" 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200