/**
 * Tests that verify the issues identified in PR #2153 review.
 *
 * Each test asserts the CORRECT expected behavior.
 * Tests FAIL on the current code, proving bugs exist.
 * Once fixed, all tests should pass.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { extractAllDumpScriptsSync } from '@/dump/html-utils';
import { ReportMergingTool } from '@/report';
import { ReportGenerator } from '@/report-generator';
import { ScreenshotItem } from '@/screenshot-item';
import {
  ExecutionDump,
  type GroupMeta,
  GroupedActionDump,
  type TestStatus,
  type UIContext,
} from '@/types';
import { getReportTpl } from '@/utils';
import { antiEscapeScriptTag, escapeScriptTag } from '@midscene/shared/utils';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

// ---------- helpers ----------

function fakeBase64(sizeBytes: number): string {
  return `data:image/png;base64,${'A'.repeat(sizeBytes)}`;
}

function fakeScreenshot(size = 200): ScreenshotItem {
  return ScreenshotItem.create(fakeBase64(size), Date.now());
}

let execIdCounter = 0;

function createExecution(
  screenshots: ScreenshotItem[],
  name = 'test-execution',
  id?: string,
): ExecutionDump {
  const tasks = screenshots.map((s, i) => ({
    taskId: `task-${i}`,
    type: 'Insight' as const,
    subType: 'Locate',
    param: { prompt: `task-${i}` },
    uiContext: {
      screenshot: s,
      shotSize: { width: 1920, height: 1080 },
      shrunkShotToLogicalRatio: 1,
    },
    executor: async () => undefined,
    recorder: [],
    status: 'running' as const,
  }));

  return new ExecutionDump({
    id: id ?? `issue-test-exec-${++execIdCounter}`,
    logTime: Date.now(),
    name,
    tasks,
  });
}

const defaultGroupMeta: GroupMeta = {
  groupName: 'test-group',
  groupDescription: 'test',
  sdkVersion: '1.0.0-test',
  modelBriefs: [],
};

function getTmpDir(prefix: string): string {
  const dir = join(tmpdir(), `midscene-issue-test-${prefix}-${Date.now()}`);
  mkdirSync(dir, { recursive: true });
  return dir;
}

// ---------- Issue 1: Viewer crashes on old reports without data-group-id ----------

describe('Issue 1: Viewer backward compatibility with old report format', () => {
  /**
   * Old reports have <script type="midscene_web_dump"> tags WITHOUT data-group-id.
   * The new App.tsx throws an Error when data-group-id is missing.
   * This test simulates what the Viewer's getDumpElements() does.
   */
  it('should parse dump scripts without data-group-id (old format)', () => {
    // Simulate an old-format dump script tag (no data-group-id attribute)
    const oldFormatDump = new GroupedActionDump({
      sdkVersion: '0.9.0',
      groupName: 'old-report',
      groupDescription: 'legacy',
      modelBriefs: [],
      executions: [
        new ExecutionDump({
          logTime: Date.now(),
          name: 'old-execution',
          tasks: [],
        }),
      ],
    });

    const serialized = oldFormatDump.serialize();
    const escapedContent = escapeScriptTag(serialized);

    // Old format: no data-group-id attribute
    const oldHtml = `<script type="midscene_web_dump" type="application/json">\n${escapedContent}\n</script>`;

    // Verify old format does NOT contain data-group-id
    expect(oldHtml).not.toContain('data-group-id');

    // The old format dump tag should still be parseable
    // App.tsx currently throws when data-group-id is missing
    // This test documents: old format tags exist and lack data-group-id
    const tagRegex = /<script type="midscene_web_dump"([^>]*)>/;
    const match = oldHtml.match(tagRegex);
    expect(match).toBeTruthy();

    // Extract attributes — no data-group-id present
    const attrString = match![1];
    expect(attrString).not.toContain('data-group-id');

    // The content is valid JSON that can be parsed
    const contentRegex =
      /<script type="midscene_web_dump"[^>]*>([\s\S]*?)<\/script>/;
    const contentMatch = oldHtml.match(contentRegex);
    expect(contentMatch).toBeTruthy();
    const parsed = JSON.parse(antiEscapeScriptTag(contentMatch![1].trim()));
    expect(parsed.groupName).toBe('old-report');
    expect(parsed.executions).toHaveLength(1);
  });

  /**
   * Merged reports generated by reportHTMLContent() also lack data-group-id.
   * This verifies the merged report format.
   */
  it('merged reports from reportHTMLContent() lack data-group-id', async () => {
    const tmpDir = getTmpDir('merged-compat');
    const tool = new ReportMergingTool();

    // Create 2 source reports using the new per-execution API
    for (let i = 0; i < 2; i++) {
      const gen = ReportGenerator.create(`compat-source-${i}`, {
        generateReport: true,
        outputFormat: 'single-html',
        autoPrintReportMsg: false,
      }) as ReportGenerator;

      const groupMeta: GroupMeta = {
        groupName: `compat-group-${i}`,
        sdkVersion: '1.0.0-test',
        modelBriefs: [],
      };
      const exec = new ExecutionDump({
        id: `compat-exec-${i}`,
        logTime: Date.now(),
        name: `exec-${i}`,
        tasks: [
          {
            type: 'Insight' as const,
            subType: 'Locate',
            param: { prompt: `task-${i}` },
            taskId: `task-${i}`,
            uiContext: {
              screenshot: fakeScreenshot(),
              shotSize: { width: 1920, height: 1080 },
              shrunkShotToLogicalRatio: 1,
            } as unknown as UIContext,
            executor: async () => undefined,
            recorder: [],
            status: 'finished' as const,
          } as any,
        ],
      });
      gen.onExecutionUpdate(exec, groupMeta);
      await gen.finalize();

      tool.append({
        reportFilePath: gen.getReportPath()!,
        reportAttributes: {
          testDescription: `Compat test ${i}`,
          testDuration: 1000,
          testId: `compat-${i}`,
          testStatus: 'passed' as TestStatus,
          testTitle: `Compat Test ${i}`,
        },
      });
    }

    const mergedPath = tool.mergeReports('compat-merged', { overwrite: true });
    expect(mergedPath).toBeTruthy();

    const mergedHtml = readFileSync(mergedPath!, 'utf-8');

    // Find all dump script tags in the merged output
    const dumpTagRegex =
      /<script type="midscene_web_dump"[^>]*>([\s\S]*?)<\/script>/g;
    const allDumpTags = [...mergedHtml.matchAll(dumpTagRegex)];

    // The merged report should have dump tags
    expect(allDumpTags.length).toBeGreaterThan(0);

    // Merged reports from reportHTMLContent() may lack data-group-id.
    // The Viewer must handle this gracefully (fallback to per-element groups).
    // Filter to real dump tags (content starts with '{') and verify parseability.
    const realDumpTags = allDumpTags.filter((m) => {
      const content = antiEscapeScriptTag(m[1].trim());
      return content.length > 0 && content.startsWith('{');
    });
    expect(realDumpTags.length).toBe(2); // one per source report
    for (const match of realDumpTags) {
      const content = antiEscapeScriptTag(match[1].trim());
      expect(() => JSON.parse(content)).not.toThrow();
    }
  });
});

// ---------- Issue 2: groupName collision ----------

describe('Issue 2: default groupName causes unrelated reports to merge', () => {
  /**
   * When multiple ReportGenerator instances use the default groupName "Midscene Report",
   * their data-group-id attributes will be identical, causing the Viewer to
   * incorrectly merge unrelated executions into one group.
   */
  it('two generators with same groupName produce identical data-group-id', async () => {
    const tmpDir = getTmpDir('groupname-collision');

    const gen1 = new ReportGenerator({
      reportPath: join(tmpDir, 'report1.html'),
      screenshotMode: 'inline',
      autoPrint: false,
    });
    const gen2 = new ReportGenerator({
      reportPath: join(tmpDir, 'report2.html'),
      screenshotMode: 'inline',
      autoPrint: false,
    });

    const sameGroupMeta: GroupMeta = {
      groupName: 'Midscene Report', // default groupName
      sdkVersion: '1.0.0',
      modelBriefs: [],
    };

    const exec1 = createExecution([fakeScreenshot()], 'exec-from-report-1');
    gen1.onExecutionUpdate(exec1, sameGroupMeta);
    await gen1.flush();

    const exec2 = createExecution([fakeScreenshot()], 'exec-from-report-2');
    gen2.onExecutionUpdate(exec2, sameGroupMeta);
    await gen2.flush();

    const html1 = readFileSync(join(tmpDir, 'report1.html'), 'utf-8');
    const html2 = readFileSync(join(tmpDir, 'report2.html'), 'utf-8');

    // Extract data-group-id from each report
    const groupIdRegex = /data-group-id="([^"]*)"/;
    const groupId1 = html1.match(groupIdRegex)?.[1];
    const groupId2 = html2.match(groupIdRegex)?.[1];

    expect(groupId1).toBeDefined();
    expect(groupId2).toBeDefined();

    // Each generator should produce a unique data-group-id, not the shared groupName.
    // Currently both are "Midscene Report" — unrelated reports will collide.
    expect(groupId1).not.toBe(groupId2);
  });
});

// ---------- Issue 3: dedup key merges unrelated old executions ----------

describe('Issue 3: dedup key merges old executions without id', () => {
  /**
   * Old ExecutionDump entries have no `id` field. The dedup logic uses
   * `exec.id || exec.name` as key. When multiple old executions share the
   * same name (e.g. "Act - click login"), they get incorrectly merged
   * (only the last one survives).
   */
  it('mergeDumpScripts loses old executions with same name and no id', async () => {
    const tmpDir = getTmpDir('dedup-old');

    const gen = new ReportGenerator({
      reportPath: join(tmpDir, 'dedup-old.html'),
      screenshotMode: 'inline',
      autoPrint: false,
    });

    const groupMeta: GroupMeta = {
      groupName: 'dedup-test',
      sdkVersion: '1.0.0',
      modelBriefs: [],
    };

    // Simulate two different executions with the SAME name but NO id
    // (as old-format data would have)
    const exec1 = new ExecutionDump({
      // no id field — simulates old format
      logTime: Date.now(),
      name: 'Act - click login',
      tasks: [
        {
          type: 'Insight' as const,
          subType: 'Locate',
          param: { prompt: 'first-click' },
          taskId: 'task-first',
          uiContext: {
            screenshot: fakeScreenshot(),
            shotSize: { width: 1920, height: 1080 },
            shrunkShotToLogicalRatio: 1,
          },
          executor: async () => undefined,
          recorder: [],
          status: 'finished' as const,
        } as any,
      ],
    });

    const exec2 = new ExecutionDump({
      // no id field — simulates old format
      logTime: Date.now() + 1000,
      name: 'Act - click login', // same name!
      tasks: [
        {
          type: 'Insight' as const,
          subType: 'Locate',
          param: { prompt: 'second-click' },
          taskId: 'task-second',
          uiContext: {
            screenshot: fakeScreenshot(),
            shotSize: { width: 1920, height: 1080 },
            shrunkShotToLogicalRatio: 1,
          },
          executor: async () => undefined,
          recorder: [],
          status: 'finished' as const,
        } as any,
      ],
    });

    // Write both executions
    gen.onExecutionUpdate(exec1, groupMeta);
    gen.onExecutionUpdate(exec2, groupMeta);
    await gen.flush();

    const html = readFileSync(join(tmpDir, 'dedup-old.html'), 'utf-8');

    // Extract all dump scripts with data-group-id
    const allDumps = extractAllDumpScriptsSync(
      join(tmpDir, 'dedup-old.html'),
    ).filter((d) => d.openTag.includes('data-group-id'));

    // There should be 2 dump tags (one per execution update)
    expect(allDumps.length).toBe(2);

    // Now simulate what the Viewer does: merge and dedup
    const allExecutions: any[] = [];
    for (const d of allDumps) {
      const content = antiEscapeScriptTag(d.content);
      const parsed = JSON.parse(content);
      allExecutions.push(...parsed.executions);
    }

    // We started with 2 executions
    expect(allExecutions.length).toBe(2);

    // Apply the dedup logic from App.tsx: only dedup by id, no-id entries kept
    let noIdCounter = 0;
    const deduped = new Map<string, any>();
    for (const exec of allExecutions) {
      const key = exec.id || `__no_id_${noIdCounter++}`;
      deduped.set(key, exec);
    }

    // Both executions should survive dedup: without an id, executions with
    // the same name are distinct and must not be collapsed.
    expect(deduped.size).toBe(2);
  });
});

// ---------- Issue 4: finalize() with zero executions ----------

describe('Issue 4: finalize() with zero execution updates', () => {
  it('should not return a file path when no executions were written', async () => {
    const tmpDir = getTmpDir('zero-exec');
    const reportPath = join(tmpDir, 'empty-report.html');

    const generator = new ReportGenerator({
      reportPath,
      screenshotMode: 'inline',
      autoPrint: false,
    });

    // finalize without any onExecutionUpdate calls
    const result = await generator.finalize();

    // No file should exist since no executions were written
    expect(existsSync(reportPath)).toBe(false);

    // finalize() should return undefined when no report was actually created
    expect(result).toBeUndefined();
  });
});

// ---------- Issue 5: destroy() doesn't write final state ----------

describe('Issue 5: final execution state may not be written', () => {
  /**
   * After the last onExecutionUpdate, if the execution's tasks change status
   * (e.g. running → finished), Agent.destroy() calls finalize() without
   * re-writing the latest state. The report will show stale task statuses.
   *
   * This test verifies the pattern at the ReportGenerator level:
   * if you flush, then mutate, then finalize — the mutation is lost.
   */
  it('mutations after last onExecutionUpdate are not captured by finalize', async () => {
    const tmpDir = getTmpDir('final-state');
    const reportPath = join(tmpDir, 'final-state.html');

    const generator = new ReportGenerator({
      reportPath,
      screenshotMode: 'inline',
      autoPrint: false,
    });

    const screenshot = fakeScreenshot();
    const execution = createExecution([screenshot], 'mutable-exec');

    // The task starts as 'running'
    expect(execution.tasks[0].status).toBe('running');

    generator.onExecutionUpdate(execution, defaultGroupMeta);
    await generator.flush();

    // Now the task finishes (agent would do this)
    (execution.tasks[0] as any).status = 'finished';

    // finalize() — does NOT re-write the execution
    await generator.finalize();

    // Read the report and check the task status
    const html = readFileSync(reportPath, 'utf-8');
    const dumpRegex =
      /<script type="midscene_web_dump"[^>]*data-group-id[^>]*>([\s\S]*?)<\/script>/g;
    const matches = [...html.matchAll(dumpRegex)];
    const lastDump = matches[matches.length - 1];
    const parsed = JSON.parse(antiEscapeScriptTag(lastDump[1]));

    // The report should reflect the final state ('finished'), not the stale
    // state ('running') that was captured before the mutation.
    expect(parsed.executions[0].tasks[0].status).toBe('finished');
  });
});
