import { describe, expect, it } from 'vitest';
import { defineNode, z } from '../src';
import { renderNodeReference } from '../src/cli/node-reference';

describe('renderNodeReference', () => {
  it.each([
    ['zebra', 'aiAsk', 'aiAssert', 'aaa', 'aiAct', 'aiTap'],
    ['zebra', 'aiAsk', 'aiAct', 'aaa', 'aiTap'],
    ['zebra', 'aiAsk', 'aiAssert', 'aaa', 'aiTap'],
  ])('prioritizes available action and assertion nodes: %j', (...names) => {
    const nodes = names.map((name) =>
      defineNode({
        name,
        description: `Runs ${name}.`,
        inputSchema: z.strictObject({}),
        execute() {},
      }),
    );
    const result = renderNodeReference(nodes);
    const expected = [
      'aiAct',
      'aiAssert',
      'aaa',
      'aiAsk',
      'aiTap',
      'zebra',
    ].filter((name) => names.includes(name));

    expect(
      [...result.markdown.matchAll(/^### `([^`]+)`$/gm)].map(
        (match) => match[1],
      ),
    ).toEqual(expected);
    expect(result.markdown).toContain(
      [
        '| Node | Description |',
        '| --- | --- |',
        ...expected.map((name) => `| ${name} | Runs ${name}. |`),
      ].join('\n'),
    );
    expect(renderNodeReference([...nodes].reverse())).toEqual(result);
    expect(nodes.map((node) => node.name)).toEqual(names);
  });

  it('renders deterministic Markdown from registered node schemas', async () => {
    const alpha = defineNode({
      name: 'alpha.node',
      title: 'Alpha node',
      description: 'Runs the alpha action.',
      stringInputKey: 'customerId',
      inputSchema: z.strictObject({
        customerId: z.string().describe('The customer ID.'),
        amount: z.number().positive().describe('The order amount.'),
      }),
      execute() {},
    });
    const beta = defineNode({
      name: 'beta.node',
      description: 'Runs the beta action.',
      stringInputKey: false,
      inputSchema: z.strictObject({ enabled: z.boolean().optional() }),
      execute() {},
    });

    const location = {
      configPath: 'midscene.config.ts',
      projects: [
        {
          name: 'web',
          files: {
            include: ['cases/**/*.{yaml,yml}'],
            exclude: ['cases/fixtures/**'],
          },
        },
      ],
    };
    const first = renderNodeReference([beta, alpha], location);
    const second = renderNodeReference([alpha, beta], location);

    expect(first).toEqual(second);
    await expect(first.markdown).toMatchFileSnapshot(
      './__snapshots__/node-reference.md',
    );
    expect(first.warnings).toEqual([]);
    expect(first.markdown).toContain(
      '<!-- Generated by `midscene-test nodes`.',
    );
    expect(first.markdown).toContain('## Workflow Step Contract');
    expect(first.markdown).toContain('## Where to use these Nodes');
    expect(first.markdown.indexOf('## Available Nodes')).toBeLessThan(
      first.markdown.indexOf('## Where to use these Nodes'),
    );
    expect(first.markdown).toContain('`cases/example.yaml`');
    expect(first.markdown).toContain('`cases[].steps`');
    expect(first.markdown).toContain(
      'cases:\n  - name: Example case\n    steps:',
    );
    expect(first.markdown).not.toContain('\nworkflow:');
    expect(first.markdown.indexOf('### `alpha.node`')).toBeLessThan(
      first.markdown.indexOf('### `beta.node`'),
    );
    expect(first.markdown).toContain('## Node Details\n\n### `alpha.node`');
    expect(first.markdown).toContain('\n#### Input Schema\n');
    expect(first.markdown).not.toMatch(/^## `/m);
    expect(first.markdown).not.toMatch(/^### Input Schema$/m);
    expect(first.markdown).toContain('**Title:** Alpha node');
    expect(first.markdown).toContain(
      '**String shorthand:** Maps to `{ customerId: value }`.',
    );
    expect(first.markdown).toContain(
      '**String shorthand:** Not supported by this Node.',
    );
    expect(first.markdown).toContain('"additionalProperties": false');
    expect(first.markdown.indexOf('"amount"')).toBeLessThan(
      first.markdown.indexOf('"customerId"'),
    );
    expect(first.markdown.endsWith('\n')).toBe(true);
    expect(first.markdown.endsWith('\n\n')).toBe(false);
    expect(first.markdown).not.toContain('\u001B[');
  });

  it('keeps undocumented and empty registries explicit', () => {
    const undocumented = renderNodeReference([
      defineNode({ name: 'legacy.node', execute() {} }),
    ]);
    expect(undocumented.warnings).toEqual([
      'node "legacy.node" has no description',
      'node "legacy.node" has no inputSchema',
    ]);
    expect(undocumented.markdown).toContain('Do not infer');
    expect(undocumented.markdown).toContain(
      '**String shorthand:** Not supported by this Node.',
    );
    expect(undocumented.markdown).toContain('Do not invent input fields');
    expect(undocumented.markdown).toContain(
      '| legacy.node | Description not declared. |',
    );

    const empty = renderNodeReference([]);
    expect(empty.warnings).toEqual([]);
    expect(empty.markdown).not.toContain('| Node | Description |');
    expect(empty.markdown).not.toContain('## Node Details');
    expect(empty.markdown).toContain(
      'No nodes are registered by the current Test Project.',
    );
  });

  it('keeps pipes, backslashes, and multiline descriptions within table cells', () => {
    const result = renderNodeReference([
      defineNode({
        name: 'custom|node',
        description: '  Choose A | B.\r\nRead C:\\temp.\nDone.  ',
        execute() {},
      }),
    ]);

    expect(result.markdown).toContain(
      '| custom\\|node | Choose A \\| B.<br>Read C:\\\\temp.<br>Done. |',
    );
  });

  it('fails instead of weakening schemas that cannot be represented', () => {
    const node = defineNode({
      name: 'date.node',
      description: 'Contains an unrepresentable date.',
      inputSchema: z.strictObject({
        value: z.date(),
      }),
      execute() {},
    });

    expect(() => renderNodeReference([node])).toThrow(
      'Cannot describe node "date.node"',
    );
  });
});
