import { describe, expect, it } from 'vitest';
import { defineNode, z } from '../src';
import { renderNodeReference } from '../src/cli/node-reference';

describe('renderNodeReference', () => {
  it('renders deterministic Markdown from registered node schemas', () => {
    const alpha = defineNode({
      name: 'alpha.node',
      title: 'Alpha node',
      description: 'Runs the alpha action.',
      inputSchema: z.strictObject({
        customerId: z.string().describe('The customer ID.'),
        amount: z.number().positive().describe('The order amount.'),
      }),
      execute() {},
    });
    const beta = defineNode({
      name: 'beta.node',
      description: 'Runs the beta action.',
      inputSchema: z.strictObject({ enabled: z.boolean().optional() }),
      execute() {},
    });

    const first = renderNodeReference([beta, alpha]);
    const second = renderNodeReference([alpha, beta]);

    expect(first).toEqual(second);
    expect(first.warnings).toEqual([]);
    expect(first.markdown).toContain(
      '<!-- Generated by `midscene-test describe-nodes`.',
    );
    expect(first.markdown).toContain('## Workflow Step Contract');
    expect(first.markdown.indexOf('## `alpha.node`')).toBeLessThan(
      first.markdown.indexOf('## `beta.node`'),
    );
    expect(first.markdown).toContain('**Title:** Alpha node');
    expect(first.markdown).toContain('"additionalProperties": false');
    expect(first.markdown.indexOf('"amount"')).toBeLessThan(
      first.markdown.indexOf('"customerId"'),
    );
    expect(first.markdown.endsWith('\n')).toBe(true);
    expect(first.markdown.endsWith('\n\n')).toBe(false);
    expect(first.markdown).not.toContain('\u001B[');
  });

  it('keeps undocumented and empty registries explicit', () => {
    const undocumented = renderNodeReference([
      defineNode({ name: 'legacy.node', execute() {} }),
    ]);
    expect(undocumented.warnings).toEqual([
      'node "legacy.node" has no description',
      'node "legacy.node" has no inputSchema',
    ]);
    expect(undocumented.markdown).toContain('Do not infer');
    expect(undocumented.markdown).toContain('Do not invent input fields');

    const empty = renderNodeReference([]);
    expect(empty.warnings).toEqual([]);
    expect(empty.markdown).toContain(
      'No nodes are registered by the current Test Project.',
    );
  });

  it('fails instead of weakening schemas that cannot be represented', () => {
    const node = defineNode({
      name: 'date.node',
      description: 'Contains an unrepresentable date.',
      inputSchema: z.strictObject({
        value: z.date(),
      }),
      execute() {},
    });

    expect(() => renderNodeReference([node])).toThrow(
      'Cannot describe node "date.node"',
    );
  });
});
