import {
  MIDSCENE_GROUNDING_MODEL_NAME,
  MIDSCENE_GROUNDING_OPENAI_API_KEY,
  MIDSCENE_GROUNDING_OPENAI_BASE_URL,
  MIDSCENE_GROUNDING_OPENAI_HTTP_PROXY,
  MIDSCENE_GROUNDING_OPENAI_INIT_CONFIG_JSON,
  MIDSCENE_GROUNDING_OPENAI_SOCKS_PROXY,
  MIDSCENE_GROUNDING_VL_MODE,
  MIDSCENE_MODEL_NAME,
  MIDSCENE_OPENAI_API_KEY,
  MIDSCENE_OPENAI_BASE_URL,
  MIDSCENE_OPENAI_HTTP_PROXY,
  MIDSCENE_OPENAI_INIT_CONFIG_JSON,
  MIDSCENE_OPENAI_SOCKS_PROXY,
  MIDSCENE_PLANNING_MODEL_NAME,
  MIDSCENE_PLANNING_OPENAI_API_KEY,
  MIDSCENE_PLANNING_OPENAI_BASE_URL,
  MIDSCENE_PLANNING_OPENAI_HTTP_PROXY,
  MIDSCENE_PLANNING_OPENAI_INIT_CONFIG_JSON,
  MIDSCENE_PLANNING_OPENAI_SOCKS_PROXY,
  MIDSCENE_PLANNING_VL_MODE,
  MIDSCENE_VL_MODE,
  // VQA
  MIDSCENE_VQA_MODEL_NAME,
  MIDSCENE_VQA_OPENAI_API_KEY,
  MIDSCENE_VQA_OPENAI_BASE_URL,
  MIDSCENE_VQA_OPENAI_HTTP_PROXY,
  MIDSCENE_VQA_OPENAI_INIT_CONFIG_JSON,
  MIDSCENE_VQA_OPENAI_SOCKS_PROXY,
  MIDSCENE_VQA_VL_MODE,
  OPENAI_API_KEY,
  OPENAI_BASE_URL,
} from './types';

interface IModelConfigKeys {
  modelName: string;
  /**
   * proxy
   */
  socksProxy: string;
  httpProxy: string;
  /**
   * OpenAI
   */
  openaiBaseURL: string;
  openaiApiKey: string;
  openaiExtraConfig: string;
  /**
   * Extra
   */
  vlMode: string;
}

export const VQA_MODEL_CONFIG_KEYS: IModelConfigKeys = {
  modelName: MIDSCENE_VQA_MODEL_NAME,
  /**
   * proxy
   */
  socksProxy: MIDSCENE_VQA_OPENAI_SOCKS_PROXY,
  httpProxy: MIDSCENE_VQA_OPENAI_HTTP_PROXY,
  /**
   * OpenAI
   */
  openaiBaseURL: MIDSCENE_VQA_OPENAI_BASE_URL,
  openaiApiKey: MIDSCENE_VQA_OPENAI_API_KEY,
  openaiExtraConfig: MIDSCENE_VQA_OPENAI_INIT_CONFIG_JSON,
  /**
   * Extra
   */
  vlMode: MIDSCENE_VQA_VL_MODE,
} as const;

export const GROUNDING_MODEL_CONFIG_KEYS: IModelConfigKeys = {
  modelName: MIDSCENE_GROUNDING_MODEL_NAME,
  /**
   * proxy
   */
  socksProxy: MIDSCENE_GROUNDING_OPENAI_SOCKS_PROXY,
  httpProxy: MIDSCENE_GROUNDING_OPENAI_HTTP_PROXY,
  /**
   * OpenAI
   */
  openaiBaseURL: MIDSCENE_GROUNDING_OPENAI_BASE_URL,
  openaiApiKey: MIDSCENE_GROUNDING_OPENAI_API_KEY,
  openaiExtraConfig: MIDSCENE_GROUNDING_OPENAI_INIT_CONFIG_JSON,
  /**
   * Extra
   */
  vlMode: MIDSCENE_GROUNDING_VL_MODE,
} as const;

export const PLANNING_MODEL_CONFIG_KEYS: IModelConfigKeys = {
  modelName: MIDSCENE_PLANNING_MODEL_NAME,
  /**
   * proxy
   */
  socksProxy: MIDSCENE_PLANNING_OPENAI_SOCKS_PROXY,
  httpProxy: MIDSCENE_PLANNING_OPENAI_HTTP_PROXY,
  /**
   * OpenAI
   */
  openaiBaseURL: MIDSCENE_PLANNING_OPENAI_BASE_URL,
  openaiApiKey: MIDSCENE_PLANNING_OPENAI_API_KEY,
  openaiExtraConfig: MIDSCENE_PLANNING_OPENAI_INIT_CONFIG_JSON,
  /**
   * Extra
   */
  vlMode: MIDSCENE_PLANNING_VL_MODE,
} as const;

// modelConfig return default
export const DEFAULT_MODEL_CONFIG_KEYS: IModelConfigKeys = {
  modelName: MIDSCENE_MODEL_NAME,
  /**
   * proxy
   */
  socksProxy: MIDSCENE_OPENAI_SOCKS_PROXY,
  httpProxy: MIDSCENE_OPENAI_HTTP_PROXY,
  /**
   * OpenAI
   */
  openaiBaseURL: MIDSCENE_OPENAI_BASE_URL,
  openaiApiKey: MIDSCENE_OPENAI_API_KEY,
  openaiExtraConfig: MIDSCENE_OPENAI_INIT_CONFIG_JSON,
  /**
   * Extra
   */
  vlMode: MIDSCENE_VL_MODE,
} as const;

// read from process.env
export const DEFAULT_MODEL_CONFIG_KEYS_LEGACY: IModelConfigKeys = {
  modelName: MIDSCENE_MODEL_NAME,
  /**
   * proxy
   */
  socksProxy: MIDSCENE_OPENAI_SOCKS_PROXY,
  httpProxy: MIDSCENE_OPENAI_HTTP_PROXY,
  /**
   * OpenAI
   */
  openaiBaseURL: OPENAI_BASE_URL,
  openaiApiKey: OPENAI_API_KEY,
  openaiExtraConfig: MIDSCENE_OPENAI_INIT_CONFIG_JSON,
  /**
   * Extra
   */
  vlMode: 'DEFAULT_MODEL_CONFIG_KEYS has no vlMode key',
} as const;
