export const EN_US = {
  // Banner - Title
  heroTitle: 'See interfaces like a human\nE2E testing in natural language',
  heroSubtitle:
    'Midscene.js helps developers bring AI to E2E testing with a vision-based GUI Agent and an extensible testing framework for web, mobile, and desktop apps.',

  // Banner - Stats
  githubStars: 'Github Stars',
  activeUsers: 'No.2 in Github trending',

  // Banner - CTA Buttons
  introduction: 'Documentation',
  whatsNew: 'Showcases',
  benchmark: 'Pass@1',
  completion: 'Completion',

  // Natural-language test example
  exampleYamlTitle: '@midscene/test + YAML test cases',
  exampleSetupOmitted: 'Model configuration, page setup, and cleanup omitted',
  exampleEyebrow: 'WRITE A TEST',
  exampleHeading: 'Describe steps and expectations in natural language',
  exampleCase: 'Find headphones under $100',
  exampleAct:
    'Search for headphones and filter the results to prices under $100',
  exampleWait: 'The filtered search results are visible',
  exampleAssert:
    'There are products in the search results, and each costs less than $100',

  // Platforms
  platformGuide: 'Get started',
  clientsTitle: 'PLATFORMS',
  clientsHeading: 'One API, across platforms',
  platformWeb: 'Web',
  platformWebAccess: 'Playwright · Puppeteer · Desktop Chrome',
  platformDesktop: 'Desktop',
  platformDesktopAccess: 'macOS · Windows · Linux, with remote RDP',
  platformAndroidAccess: 'Devices / emulators · ADB',
  platformIosAccess: 'Devices / simulators · WebDriverAgent',
  platformHarmonyAccess: 'HarmonyOS NEXT · HDC',
  platformCustom: 'Custom interfaces',
  platformCustomAccess: 'Connect through screenshots and actions',
  platformCustomDoc: 'Extension guide',
  platformBridgeDoc: 'Bridge Mode',

  // Feature Sections - MODELS
  modelsTitle: 'VISION MODELS & STRATEGY',
  modelsHeading: 'Vision-driven\nLow-cost testing',

  // Model Cards
  modelVisionName: 'Locate and act from screenshots',
  modelVisionDesc:
    'Locate elements and operate interfaces from screenshots, without maintaining selectors or annotations. Works with custom interfaces such as Canvas.',
  modelVisionMetric: 'Screenshot → Locate → Act',
  modelAssertName: 'Verify what users see',
  modelAssertDesc:
    'Describe expected colors, layouts, and states in natural language. Visual assertions check what the interface actually shows.',
  modelAssertMetric: 'Colors · Layouts · States',
  modelSupportedName: 'Multiple model options',
  modelSupportedDesc:
    'Choose from Doubao, DeepSeek, Qwen, GPT, Gemini, Kimi, and more to fit your tasks and budget.',
  modelCostName: 'Low model API cost',
  modelCostDesc:
    'In this AppControlBench run, Doubao Seed 2.1 Turbo passed 58 of 60 tasks at a total model API cost of $0.59.',
  modelCostExample: 'Benchmark example · AppControlBench',
  modelCostReport: 'View benchmark report',
  modelCostMetric: 'Total model API cost for 60 tasks',

  // Test framework
  frameworkHeading: 'YAML for test cases\nTypeScript for extensions',
  frameworkYamlTitle: 'Organize cases in natural language',
  frameworkYamlDesc:
    'Combine UI actions, assertions, and business Nodes in YAML to describe your test flows.',
  frameworkNodeTitle: 'Make business operations reusable',
  frameworkNodeDesc:
    'Implement data setup, API calls, and cleanup in TypeScript Nodes that different cases can reuse.',
  frameworkSpecTitle: 'Generate a Node Spec automatically',
  frameworkSpecDesc:
    'Export registered Nodes and input schemas as Markdown so developers and AI agents can discover project capabilities and maintain tests together.',
  frameworkSpecOmitted:
    'Remaining schema fields and Node descriptions omitted.',
  frameworkSpecNote:
    'Generated by pnpm exec midscene-test nodes. This excerpt describes user.create and matches its TypeScript definition.',
  frameworkLink: 'Explore Midscene Test',
  frameworkYamlTab: 'YAML cases',
  frameworkNodeTab: 'TypeScript extensions',
  frameworkCase: 'Find a new user',
  frameworkAct: 'Search for the user Alice',
  frameworkAssert: 'The search results show the user Alice',
  frameworkNodeDescription: 'Create a test user and clean up after the case',
  frameworkYamlNote:
    'Example: prepare user data, then search and verify through the UI. Configure a model and Web environment first, and replace the example URL.',
  frameworkNodeNote:
    'user.create matches the YAML step. Implement userService with your business APIs to create and delete test users.',

  // Testing toolkit
  debuggingTitle: 'TESTING TOOLKIT',
  debuggingHeading: 'A complete toolkit for AI-native testing',
  toolkitFrameworkTitle: 'An AI-native testing framework',
  toolkitFrameworkDesc:
    'Write tests in YAML and natural language. Extend them with TypeScript Nodes to combine AI actions with business logic.',
  toolkitYaml: 'Test flows & expectations',
  toolkitTs: 'Custom business Nodes',
  toolkitEngineering:
    'Scaffolding, platform presets, lifecycle hooks, retries, isolation, and concurrency.',
  toolkitNodeDocs:
    'Generate Node references so people and AI agents can maintain tests together.',
  toolkitFrameworkLink: 'Explore Midscene Test',
  toolkitApiMetric: 'Actions · Assertions · Data extraction',
  toolkitSkillsTitle: 'Let AI coding agents operate your UI',
  toolkitSkillsDesc:
    'Give AI coding agents Midscene Skills to operate apps, verify interfaces, and inspect execution results.',
  toolkitApiTitle: 'Rich, flexible APIs',
  toolkitApiDesc:
    'Bring autonomous flows, precise actions, visual assertions, and data extraction into your existing test stack.',
  toolkitPlan: 'Autonomous flows',
  toolkitAction: 'Precise actions',
  toolkitAssert: 'Visual assertions',
  toolkitQuery: 'Data extraction',
  toolkitIntegration:
    'Integrate with Playwright, Puppeteer, or JavaScript. AI coding agents can also operate interfaces through Skills.',
  toolkitApiLink: 'Explore APIs',
  toolkitSkillsLink: 'Skills',
  toolkitReportTitle: 'Replay runs, debug interactively',
  toolkitReportDesc:
    'Review screenshots, AI decisions, and execution results in reports. Try and refine instructions in the Playground.',
  toolkitPlaygroundDesc:
    'Investigate failures with runtime logs. Try and refine instructions in the Playground.',
  toolkitReportAlt:
    'Midscene HTML report with an action list, execution timeline, and interface replay',
  toolkitReportLink: 'Explore reporting',
  toolkitPlaygroundLink: 'Try the Playground',

  // Feature Sections - BENCHMARKS
  benchmarksTitle: 'EVALUATION',
  benchmarksHeading: 'Benchmarks',

  // Feature Cards
  featureRichAPIs: 'Rich APIs',
  featureRichAPIsDesc:
    'Auto-planning for whole flows, plus atomic APIs like aiTap and aiAssert for precise tests.',
  featureSkills: 'Skills',
  featureSkillsDesc:
    'Drop-in Skills let AI coding agents test your UI through Midscene CLIs.',
  featureReportsPlayground: 'Reports & Playground',
  featureReportsPlaygroundDesc:
    'Replay every step in a visual report, and try ideas fast in the playground.',
  featureFlexibleIntegration: 'Flexible Integration',
  featureFlexibleIntegrationDesc:
    'Write tests in YAML with Midscene Test and extend them with custom TypeScript Nodes.',
  featureRichAPIsLink: '/reference/',
  featureSkillsLink: '/skills',
  featureReportsPlaygroundLink: '/quick-start#chrome-extension',
  featureFlexibleIntegrationLink: '/midscene-test/overview',
  featureBenchmarkLink: '/android-world-benchmark-report',
  featureMobileWorldBenchmarkLink: '/mobile-world-benchmark-report',
  featureAppControlBenchLink: '/app-control-bench-report',

  // View All APIs
  apiMoreLink: 'View All APIs',
  apiMoreDesc:
    'Explore the complete API documentation for more automation capabilities.',

  // Who is Using
  whoIsUsingEyebrow: 'USERS',
  whoIsUsingTitle: 'Who is using Midscene',
  userVolcengine: 'Volcengine',
  userDouyin: 'Douyin',
  userAlibaba: 'Alibaba',
  userCtrip: 'Ctrip',
  userXiaomi: 'Xiaomi',
  userIqiyi: 'iQIYI',
  userLark: 'Lark',
  userSodaMusic: 'Soda Music',
  userBilibili: 'Bilibili',
  userBilibiliLogo: '/images/users/bilibili-color.svg',
  userBilibiliLogoWidth: '90',
  userDoubao: 'Doubao',
  userDongchedi: 'Dongchedi',

  // Bottom CTA and Footer
  bottomCtaTitle: 'Write your first E2E test in natural language',
  bottomCtaStart: 'Get started',
  bottomCtaExamples: 'Explore examples',
  licenseNotice:
    'Midscene is free and open source software released under the MIT license.',
  copyrightNotice: '© 2024-present ByteDance Inc. and its affiliates.',
} as const;
