name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
      
permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.13.0]

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      with:
        fetch-depth: 0

    - name: Fetch all branches
      run: git fetch --all

    - name: Setup pnpm
      uses: pnpm/action-setup@eae0cfeb286e66ffb5155f1a79b90583a127a68b # v2.4.1
      with:
        version: 9.3.0
  
    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: '24.13.0'
        cache: 'pnpm'

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile --ignore-scripts

    - name: Check Dependency Version
      run: pnpm run check-dependency-version

    - name: Biome lint
      run: npx biome check . --diagnostic-level=warn --no-errors-on-unmatched
